DROP TABLE IF EXISTS BATTERY;

CREATE TABLE BATTERY (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	postcode VARCHAR(16) NOT NULL,
	capacity REAL NOT NULL
);

CREATE INDEX PostcodeIndex ON BATTERY (postcode);
